# Generated by Django 4.1.6 on 2023-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('product_url', models.URLField()),
                ('info_url', models.URLField()),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
