# Generated by Django 3.2.7 on 2021-10-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('arrival', models.DateTimeField(verbose_name='Arrival')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.station', verbose_name='Station')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('start', models.DateTimeField(verbose_name='Starts')),
                ('ends', models.DateTimeField(verbose_name='Ends')),
                ('travel_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inbound', to='events.travel', verbose_name='From')),
                ('travel_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='outbound', to='events.travel', verbose_name='To')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.venue')),
            ],
        ),
    ]
