# Generated by Django 3.2.7 on 2021-11-30 14:07

import django.db.models.deletion
from django.db import migrations, models

import events.models
import Intranet.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('start', models.DateTimeField(verbose_name='Starts')),
                ('ends', models.DateTimeField(verbose_name='Ends')),
                ('ticket_file', models.FileField(blank=True, null=True, storage=Intranet.misc.OverwriteStorage, upload_to=events.models.ticket_file_name)),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('arrival', models.DateTimeField(verbose_name='Arrival')),
                ('direction', models.CharField(choices=[('To', 'To'), ('From', 'From')], max_length=4)),
                ('ticket_file', models.FileField(blank=True, null=True, storage=Intranet.misc.OverwriteStorage, upload_to=events.models.travel_file_name)),
                ('notes', models.TextField(max_length=500)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrival_station', to='events.station', verbose_name='Arrival Station')),
                ('departing_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departing_station', to='events.station', verbose_name='Departing Station')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event', to='events.event', verbose_name='For Event')),
                ('travel_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='travel_type', to='events.traveltype', verbose_name='Travel Type')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travel',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.venue'),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Check In')),
                ('check_out', models.DateTimeField(verbose_name='Check Out')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_accommodation', to='events.event', verbose_name='Event')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_hotel', to='events.hotel', verbose_name='Hotel')),
            ],
        ),
    ]
