# Generated by Django 3.2.7 on 2021-10-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='travel_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='travel_to',
        ),
        migrations.AddField(
            model_name='travel',
            name='direction',
            field=models.CharField(choices=[('To', 'To'), ('From', 'From')], default='To', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='event', to='events.event', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
