# Generated by Django 3.2.6 on 2021-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
