# Generated by Django 3.2.6 on 2021-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210828_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='file',
        ),
    ]
