# Generated by Django 3.2.7 on 2021-10-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211021_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Travel', 'verbose_name_plural': 'Travel'},
        ),
        migrations.RemoveField(
            model_name='travel',
            name='station',
        ),
        migrations.AddField(
            model_name='travel',
            name='arrival_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='arrival_station', to='events.station', verbose_name='Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='departing_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='departing_station', to='events.station', verbose_name='Station'),
            preserve_default=False,
        ),
    ]
