# Generated by Django 4.1.6 on 2023-02-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_notes_alter_event_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accommodation',
            constraint=models.CheckConstraint(check=models.Q(('check_out__gte', models.F('check_in'))), name='check_in_before_checkout'),
        ),
    ]
