# Generated by Django 3.2.7 on 2021-10-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211021_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_file',
            field=models.FileField(default=1, upload_to='C:\\Users\\Peter\\AppData\\Local\\Temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='for_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='event', to='events.event', verbose_name='For Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='notes',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='ticket_file',
            field=models.FileField(default=1, upload_to='C:\\Users\\Peter\\AppData\\Local\\Temp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='arrival_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrival_station', to='events.station', verbose_name='Arrival Station'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='departing_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departing_station', to='events.station', verbose_name='Departing Station'),
        ),
    ]
