# Generated by Django 3.2.6 on 2021-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
