# Generated by Django 3.2.6 on 2021-08-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='where',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.venue'),
        ),
    ]
