# Generated by Django 4.1.6 on 2023-02-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_accommodation_check_in_before_checkout'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accommodation',
            name='check_in_before_checkout',
        ),
        migrations.AddConstraint(
            model_name='accommodation',
            constraint=models.CheckConstraint(check=models.Q(('check_out__gt', models.F('check_in'))), name='check_in_before_checkout'),
        ),
    ]
