# Generated by Django 3.2.7 on 2021-10-21 23:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211022_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://google.com/tickets', location='C:\\Users\\Peter\\AppData\\Local\\Temp'), upload_to=''),
        ),
    ]
