# Generated by Django 3.2.6 on 2021-09-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210828_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('To', 'To'), ('From', 'From')], max_length=4)),
                ('starting', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.event')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.transportmethods')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.venue')),
            ],
        ),
    ]
