# Generated by Django 3.2.6 on 2021-09-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventtravel_transportmethods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransportMethods',
            new_name='TransportMethod',
        ),
    ]
