# Generated by Django 3.2.7 on 2021-10-21 23:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_travel_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://google.com/events', location='C:\\Users\\Peter\\AppData\\Local\\Temp'), upload_to=''),
        ),
    ]
