# Generated by Django 3.2.6 on 2021-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_transportmethods_transportmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtravel',
            name='starting',
            field=models.DateTimeField(),
        ),
    ]
