# Generated by Django 3.2.7 on 2021-10-22 00:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://nas.devfaq.com/events', location='/tmp/events'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='travel',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://nas.devfaq.com/travel', location='/tmp/travel'), upload_to=''),
        ),
    ]
