# Generated by Django 3.2.6 on 2021-09-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventtravel_starting'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtravel',
            name='ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
