# Generated by Django 3.2 on 2021-04-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('description', models.CharField(max_length=500)),
                ('connected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.device')),
                ('connection_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.connectionmethod')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_topology.devicetype')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network_topology.ip')),
            ],
        ),
    ]
