# Generated by Django 3.1.7 on 2021-04-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='connection_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.connectionmethod'),
        ),
    ]
