# Generated by Django 3.1.7 on 2021-04-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.device'),
        ),
    ]
