# Generated by Django 3.2 on 2021-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0002_ansiblegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ansible_group',
            field=models.ManyToManyField(to='network_topology.AnsibleGroup'),
        ),
    ]
