# Generated by Django 3.1.7 on 2021-04-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0002_auto_20210405_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
