# Generated by Django 3.2.2 on 2021-05-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0002_rename_ansible_group_device_monitoring_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='monitoring_group',
            new_name='monitoring_groups',
        ),
    ]
