# Generated by Django 3.2 on 2021-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0003_device_ansible_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ansible_group',
            field=models.ManyToManyField(blank=True, null=True, to='network_topology.AnsibleGroup'),
        ),
    ]
