# Generated by Django 3.2.2 on 2021-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0003_rename_monitoring_group_device_monitoring_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='monitoring_groups',
            field=models.ManyToManyField(to='network_topology.MonitoringGroup'),
        ),
    ]
