# Generated by Django 3.2 on 2021-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0004_alter_device_ansible_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblegroup',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
