# Generated by Django 3.2.2 on 2021-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0004_alter_device_monitoring_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
