# Generated by Django 3.1.7 on 2021-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0004_auto_20210405_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
