# Generated by Django 3.2.6 on 2021-08-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0005_device_snmp_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionmethod',
            options={'verbose_name': 'Connection Method', 'verbose_name_plural': 'Connection Methods'},
        ),
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'verbose_name': 'Device Category', 'verbose_name_plural': 'Device Categories'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'IP', 'verbose_name_plural': 'IPs'},
        ),
        migrations.AlterModelOptions(
            name='monitoringgroup',
            options={'verbose_name': 'Monitoring Group', 'verbose_name_plural': 'Monitoring Groups'},
        ),
        migrations.AlterModelOptions(
            name='monitoringtemplate',
            options={'verbose_name': 'Monitoring Template', 'verbose_name_plural': 'Monitoring Templates'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
