# Generated by Django 3.2.6 on 2021-08-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0006_auto_20210822_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='url',
        ),
        migrations.AddField(
            model_name='site',
            name='https',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='use_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network_topology.registrar')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_topology.domain'),
        ),
    ]
