# Generated by Django 3.2 on 2021-04-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0006_devicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.devicecategory'),
            preserve_default=False,
        ),
    ]
