# Generated by Django 3.2.6 on 2021-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0007_auto_20210826_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='use_api',
            field=models.BooleanField(default=False),
        ),
    ]
