# Generated by Django 3.2 on 2021-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0007_devicetype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='ansible_group',
            field=models.ManyToManyField(blank=True, to='network_topology.AnsibleGroup'),
        ),
    ]
