# Generated by Django 3.2.6 on 2021-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0008_registrar_use_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
