# Generated by Django 3.2.6 on 2021-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0009_device_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('use_api', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='dns_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
