# Generated by Django 3.2.6 on 2021-08-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0010_auto_20210827_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='network_topology.dnsprovider'),
            preserve_default=False,
        ),
    ]
