# Generated by Django 3.2.6 on 2021-08-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0011_alter_domain_dns_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsprovider',
            options={'verbose_name': 'DNS Provider', 'verbose_name_plural': 'DNS Providers'},
        ),
    ]
