default_language_version:
  python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    name: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.940'
  hooks:
  - id: mypy
    name: mypy
    additional_dependencies: [mypy-extensions, types-pytz, types-PyYAML, types-requests, types-urllib3, typing_extensions]
