# Generated by Django 3.2.6 on 2021-08-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
