# Generated by Django 3.2.7 on 2021-10-24 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Merchant')),
                ('for_lender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.lender')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='Amount')),
                ('pending', models.BooleanField(default=False, verbose_name='Pending')),
                ('when', models.DateTimeField(verbose_name='Created')),
                ('settled', models.DateTimeField(blank=True, null=True, verbose_name='Settled')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.merchant')),
            ],
        ),
    ]
