# Generated by Django 3.2.7 on 2021-12-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monzo',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='monzo',
            name='expiry',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='monzo',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Refresh Token'),
        ),
    ]
