# Generated by Django 3.2.6 on 2021-09-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_investment_investmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenthistory',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.investment'),
        ),
    ]
