# Generated by Django 4.0.3 on 2022-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bill_billtype_paidfrom_billhistory_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtype',
            name='description',
        ),
    ]
