# Generated by Django 3.2.7 on 2021-10-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_merchant_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='for_lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.lender'),
        ),
    ]
