# Generated by Django 4.0.3 on 2022-04-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_billtype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billhistory',
            old_name='transaction_value',
            new_name='current_balance',
        ),
    ]
