# Generated by Django 3.2.7 on 2021-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_merchant_for_lender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='Client Secret')),
                ('owner_id', models.CharField(max_length=100, verbose_name='Owner ID')),
                ('access_token', models.CharField(max_length=100, verbose_name='Access Token')),
                ('expiry', models.BigIntegerField(verbose_name='Expiry')),
                ('refresh_token', models.CharField(max_length=100, verbose_name='Refresh Token')),
            ],
        ),
    ]
