# Generated by Django 4.0.3 on 2022-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_investments_investment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='investment_document',
            field=models.FileField(blank=True, null=True, upload_to='SiteDocuments/investments/'),
        ),
    ]
