# Generated by Django 4.0.3 on 2022-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_bill_options_alter_billtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
