# Generated by Django 4.0.3 on 2022-08-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_bill_last_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("client_id", models.CharField(max_length=50)),
                ("client_secret", models.CharField(max_length=100)),
                ("expiry", models.IntegerField(blank=True, max_length=10, null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
