# Generated by Django 4.0.3 on 2022-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_monzo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monzo",
            name="expiry",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
