# Generated by Django 4.0.3 on 2022-08-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_monzo_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="monzo",
            name="last_fetched_datetime",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
    ]
