# Generated by Django 4.0.3 on 2022-08-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_monzo_last_fetched_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonzoMerchant',
            fields=[
                ('merchant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MonzoTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=5)),
                ('value', models.IntegerField(max_length=10)),
                ('created', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('has_receipt', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.monzomerchant')),
            ],
        ),
    ]
