# Generated by Django 4.0.3 on 2022-08-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_monzomerchant_monzotransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monzotransaction',
            name='value',
            field=models.IntegerField(),
        ),
    ]
