# Generated by Django 4.1 on 2022-08-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_monzotransaction_for_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monzotransaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.monzomerchant'),
        ),
    ]
