# Generated by Django 4.1 on 2022-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_monzotransaction_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='monzomerchant',
            name='for_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bill'),
        ),
    ]
