# Generated by Django 4.1 on 2022-09-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_monzomerchant_for_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date_purchased',
            field=models.DateField(),
        ),
    ]
