# Generated by Django 4.0.3 on 2022-04-10 11:54

from django.db import migrations, models

import books.models
import intranet.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "subtitle",
                    models.CharField(blank=True, default=None, max_length=500),
                ),
                ("publisher", models.CharField(max_length=200)),
                ("published", models.DateField()),
                ("isbn10", models.CharField(max_length=10, unique=True)),
                ("isbn13", models.CharField(max_length=13, unique=True)),
                ("description", models.CharField(max_length=5000)),
                ("pages", models.IntegerField()),
                (
                    "thumbnail",
                    models.URLField(blank=True, default=None, max_length=255),
                ),
                (
                    "ebook",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=intranet.helpers.OverwriteStorageName,
                        upload_to=books.models.content_file_name,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("authors", models.ManyToManyField(to="books.author")),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
