# Generated by Django 4.0.3 on 2022-04-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
