# Generated by Django 3.2.6 on 2021-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210822_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
