# Generated by Django 3.2.6 on 2021-08-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210822_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.BigIntegerField(unique=True),
        ),
    ]
