# Generated by Django 3.2.6 on 2021-08-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_url',
            field=models.URLField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, default=None, max_length=255),
        ),
    ]
