# Generated by Django 3.2.6 on 2021-08-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210823_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebook_url',
            field=models.URLField(blank=True, default=None, max_length=400, verbose_name='eBook URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
