# Generated by Django 4.0.3 on 2022-04-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unique_port', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.domainname')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secure', models.BooleanField(default=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_username', models.CharField(blank=True, max_length=255, null=True)),
                ('default_password', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.operatingsystem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='domainname',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.registrar'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True, unique=True)),
                ('rack_shelf', models.IntegerField(blank=True, null=True)),
                ('rack_shelf_position', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applications', models.ManyToManyField(to='network.application')),
                ('connected_too', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.device')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.connectiontype')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.devicetype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.model')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.operatingsystem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vendor')),
            ],
        ),
    ]
