# Generated by Django 3.2.7 on 2021-11-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='Hostname')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Manufacturer')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Device Type')),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Domain Name')),
            ],
            options={
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystemVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Operating System Vendor')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Registrar')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=200, unique=True, verbose_name='Subdomain')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.device')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.domains')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('secure', models.BooleanField(default=True, verbose_name='Secure')),
                ('path', models.CharField(max_length=200, unique=True, verbose_name='Path')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, unique=True, verbose_name='Version')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.operatingsystemvendor')),
            ],
        ),
        migrations.AddField(
            model_name='domains',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.registrar'),
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Model')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.devicemanufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.ip'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.operatingsystemversion'),
        ),
    ]
