# Generated by Django 4.0.3 on 2022-04-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_device_hostname_alter_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='connected_too',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.connectiontype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.operatingsystem'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.vendor'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.registrar'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.vendor'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.operatingsystem'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.vendor'),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.subdomain'),
        ),
        migrations.AlterUniqueTogether(
            name='subdomain',
            unique_together={('name', 'domain_name')},
        ),
    ]
