# Generated by Django 3.2.7 on 2021-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_device_connected_too'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
    ]
