# Generated by Django 3.2.7 on 2021-12-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_website_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
