# Generated by Django 4.0.3 on 2022-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_vendor_device_hardware_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, to='network.application'),
        ),
    ]
