# Generated by Django 4.0.3 on 2022-04-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='network.domainname'),
        ),
    ]
