# Generated by Django 4.0.3 on 2022-04-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_subdomain_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='hosted_on',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='network.device'),
            preserve_default=False,
        ),
    ]
