# Generated by Django 4.0.3 on 2022-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_operatingsystem_alias_additionalansiblegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='additional_ansible_groups',
        ),
        migrations.AddField(
            model_name='device',
            name='additional_ansible_groups',
            field=models.ManyToManyField(to='network.additionalansiblegroup'),
        ),
    ]
