# Generated by Django 4.0.3 on 2022-04-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_device_additional_ansible_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleDeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('for_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.device')),
            ],
            options={
                'verbose_name': 'Ansible device configuration',
                'verbose_name_plural': 'Ansible device configurations',
            },
        ),
    ]
