# Generated by Django 4.0.3 on 2022-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_ansibledeviceconfiguration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ansibledeviceconfiguration',
            unique_together={('for_device', 'name')},
        ),
    ]
