# Generated by Django 4.0.3 on 2022-04-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_ansibledeviceconfiguration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='applications',
            field=models.ManyToManyField(to='network.application'),
        ),
    ]
