# Generated by Django 4.0.3 on 2022-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_device_additional_ansible_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='additional_ansible_groups',
            field=models.ManyToManyField(blank=True, to='network.additionalansiblegroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='applications',
            field=models.ManyToManyField(blank=True, to='network.application'),
        ),
    ]
