# Generated by Django 4.1.6 on 2023-02-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_device_wol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.subdomain'),
        ),
    ]
