# Generated by Django 4.1.6 on 2023-02-23 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_website_subdomain'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subdomain',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='hosted_on',
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Subdomain', 'verbose_name_plural': 'Subdomains'},
        ),
        migrations.AddField(
            model_name='website',
            name='domain_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.domainname'),
        ),
        migrations.AddField(
            model_name='website',
            name='hosted_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='network.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('name', 'domain_name')},
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('subdomain', 'domain_name'), name='unique_subdomain_on_domain'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('name', 'hosted_on'), name='unique_name_hosted_on'),
        ),
        migrations.DeleteModel(
            name='Subdomain',
        ),
    ]
