# Generated by Django 4.1.6 on 2023-02-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_alter_subdomain_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_subdomain_on_domain',
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_name_hosted_on',
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('domain_name', 'port', 'subdomain'), name='unique_subdomain_on_domain'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('hosted_on', 'port'), name='unique_port_hosted_on'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('subdomain__isnull', True), ('domain_name__isnull', True)), models.Q(('subdomain__isnull', False), ('domain_name__isnull', False)), _connector='OR'), name='subdomain_or_ip'),
        ),
    ]
