# Generated by Django 4.1.6 on 2023-02-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_alter_website_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_subdomain_on_domain',
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_port_hosted_on',
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='subdomain_or_ip',
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('domain_name', 'port', 'subdomain'), name='website_unique_subdomain_port'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('hosted_on', 'port'), name='website_unique_port_hosted_on'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('subdomain__isnull', True), ('domain_name__isnull', True)), models.Q(('subdomain__isnull', False), ('domain_name__isnull', False)), _connector='OR'), name='website_subdomain_or_ip'),
        ),
    ]
