# Generated by Django 4.1.6 on 2023-03-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_website_unique_subdomain_on_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ansible variable',
                'verbose_name_plural': 'Ansible variables',
            },
        ),
        migrations.AlterField(
            model_name='ansibledeviceconfiguration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ansiblevariables'),
        ),
    ]
