# Generated by Django 4.0.3 on 2022-04-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
