# Generated by Django 4.0.3 on 2022-04-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('name',), 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
