# Generated by Django 4.0.3 on 2022-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to="downloads/documents/"),
        ),
    ]
