# Generated by Django 4.0.3 on 2022-08-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('days_to_add', models.IntegerField(default=0, max_length=2)),
                ('months_to_add', models.IntegerField(default=0, max_length=2)),
                ('years_to_add', models.IntegerField(default=0, max_length=2)),
            ],
            options={
                'verbose_name': 'Task Frequency',
                'verbose_name_plural': 'Task Frequencies',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tasks.taskfrequency'),
        ),
    ]
