# Generated by Django 4.1.6 on 2023-02-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('updated_at__gte', models.F('created_at'))), name='task_updated_after_created'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('due_by__gte', models.F('created_at'))), name='task_due_by_after_created'),
        ),
    ]
