# Generated by Django 3.1.7 on 2021-04-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0001_initial'),
        ('network_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network_topology.ip'),
        ),
    ]
