# Generated by Django 3.1.7 on 2021-04-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_sites', '0003_auto_20210405_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='hostname',
            new_name='url',
        ),
    ]
